### PR TITLE
Cope with unicode data being part of an error

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Add a util to recursively encode a dict as utf-8 and use this before attmpting to urlencode the data for sending. This assumes that the receiving end will cope with data encoded like this, though will
avoid errors appearing for clients who pass unicode data to the Error classes.

See tests for example cases which previously caused errors. In both cases the error seen was an `UnicodeEncodeError` in `urlencode`.

### CODE REVIEW

**Comment by lamby** [comment]
Extra info:

> I spotted a case in our errors where django-keyerror hits an error
> when some of the data it's given contains unicode characters. This
> only seems to be the case when unicode objects are directly provided
> as values for the Error instances, though this can occur when the
> ident of a grouped error is unicode as well as a couple of other
> cases.
> 
> I suspect that most of the instances of this are silenced by the
> internal silencing django-keyerror does, so I'm not sure how often
> this happens.

**Comment by lamby** [comment]
@PeterJCLaw Could you confirm that — without this change — the error occurs on the django-keyerror side or that the request 500s?

**Comment by PeterJCLaw** [comment]
@lamby I saw an error report (in KeyError) for a `UnicodeEncodeError` trace which originated in django-keryerror's use of `urllib.urlencode`. Is that what you mean?

**Comment by lamby** [comment]
> I saw an error report (in KeyError) for a UnicodeEncodeError trace which originated in django-keryerror's use of urllib.urlencode. Is that what you mean?

Not exactly but it answers my question; thanks!

**Comment by lamby** [comment]
Released as ``3.1.1``. :)

**Pull request merged**
